{
 "title": "OpenMLDB dashboard",
 "description": "Grafana dashboard for https://github.com/4paradigm/OpenMLDB",
 "tags": [ "openmldb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(openmldb_status, job)"
    }
   },
   {
    "name": "component_job",
    "label": "Component Job",
    "query": {
     "query": "label_values(process_uptime, job)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(process_uptime, instance)"
    }
   },
   {
    "name": "table_path",
    "label": "Table Path",
    "query": {
     "query": "label_values(openmldb_table_rows, table_path)"
    }
   },
   {
    "name": "tablet_endpoint",
    "label": "Tablet Endpoint",
    "query": {
     "query": "label_values(openmldb_tablet_memory_application_bytes, endpoint)"
    }
   },
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "label_values({__name__=~\".*_deployment_count\"},db)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values({__name__=~\".*_deployment_count\",db=\"$db\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "OpenMLDB Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Component Status",
   "type": "stat",
   "description": "whether a component is online or offline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openmldb_status{job=~\"$job\", openmldb_status=\"online\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{endpoint}}-{{role}}"
    }
   ]
  },
  {
   "title": "Component Connected Time",
   "type": "stat",
   "description": "connected time in seconds for each components in the OpenMLDB cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openmldb_connected_seconds_total{job=~\"$job\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{endpoint}}-{{role}}"
    }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_memory_virtual{job=~\"$component_job\", instance=~\"$endpoint\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Query RPC Request ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=~\"rpc_server_.*_openmldb_api_tablet_server_query_count\", job=~\"$component_job\"})"
    }
   ]
  },
  {
   "title": "Total Sub Query RPC Request ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=~\"rpc_server_.*_openmldb_api_tablet_server_sub_query_count\", job=~\"$component_job\"})"
    }
   ]
  },
  {
   "title": "Total Batch Request Query RPC Request $endpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=~\"rpc_server_.*_openmldb_api_tablet_server_sqlbatch_request_query_count\", job=~\"$component_job\"})"
    }
   ]
  },
  {
   "title": "Total Sub Batch Request Query RPC Request ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=~\"rpc_server_.*_openmldb_api_tablet_server_sub_batch_request_query_count\", job=~\"$component_job\"})"
    }
   ]
  },
  {
   "title": "Table Row Count Total",
   "type": "stat",
   "description": "Table Rows Count for all tables",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openmldb_table_rows{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Table Memory Used Total",
   "type": "stat",
   "description": "Table Memory Used for all tables",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openmldb_table_memory_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Table Disk Used Total",
   "type": "stat",
   "description": "Table Disk Used for all tables",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (openmldb_table_disk_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Table Status-$table_path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "table_path",
   "collapsed": true,
   "panels": [
    {
     "title": "Table Partition Number",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openmldb_table_partitions{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    },
    {
     "title": "Table Replica Number",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openmldb_table_replica{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    },
    {
     "title": "Table Rows Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openmldb_table_rows{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    },
    {
     "title": "Table Memory Used",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openmldb_table_memory_bytes{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    },
    {
     "title": "Table Disk Used",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openmldb_table_disk_bytes{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    },
    {
     "title": "Table Partition Unalive Number",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openmldb_table_partitions_unalive{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    },
    {
     "title": "Table Rows",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "openmldb_table_rows{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    },
    {
     "title": "Table Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "openmldb_table_memory_bytes{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    },
    {
     "title": "Table Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "openmldb_table_disk_bytes{job=~\"$job\", table_path=~\"$table_path\"}",
       "legendFormat": "{{table_path}}-{{tid}}-{{storage_mode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deploy Query Response Time: $db.$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "deploy_path",
   "collapsed": true,
   "panels": [
    {
     "title": "Deploy Query Count $db.$deployment",
     "type": "timeseries",
     "description": "calc in recent 75s(by default, specified by [-bvar_dump_interval])\\nif requests < 60 in whole interval, qps will be 0",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum({__name__=~\".*_deployment_count\", db=\"$db\", deployment=~\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Deploy Query  QPS $db.$deployment",
     "type": "timeseries",
     "description": "calc in recent 75s(by default, specified by [-bvar_dump_interval])",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum({__name__=~\".*_deployment_qps\", db=\"$db\", deployment=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "avg/0.80/0.90/0.99/0.999/0.9999 quantile for deploy query response time $db.$deployment",
     "type": "timeseries",
     "description": "calc in recent 75s(by default, specified by [-bvar_dump_interval])",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\".*_deployment_latency\", db=\"$db\", deployment=\"$deployment\"}, \"quantile\", \"avg\", \"quantile\", \"\")",
       "legendFormat": "{{instance}}-{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Component Status: $endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "endpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Component Uptime $endpoint",
     "type": "stat",
     "description": "Uptime for a single component, whether connected to the cluster is not considered",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Cpu Usage $endpoint",
     "type": "gauge",
     "description": "Uptime for a single component, whether connected to the cluster is not considered",
     "gridPos": { "h": 5, "w": 4, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RPC Connection Count $endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rpc_channel_connection_count{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Thread Count $endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 13, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " process_thread_count{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FD Count $endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_fd_count{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BThread Count $endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bthread_count{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cpu Usage $endpoint",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}-all"
      },
      {
       "expr": "process_cpu_usage_user{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}-user"
      },
      {
       "expr": "process_cpu_usage_system{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}-system"
      }
     ]
    },
    {
     "title": "Virtual Memory  $endpoint",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_memory_virtual{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IO $endpoint",
     "type": "timeseries",
     "description": "bytes read/write per second",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": " process_io_read_bytes_second{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}-read-per-second"
      },
      {
       "expr": " process_io_write_bytes_second{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}-read-per-second"
      }
     ]
    },
    {
     "title": " Disk Usage $endpoint",
     "type": "timeseries",
     "description": "bytes read/write per second",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_disk_read_bytes_second{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}-read-per-second"
      },
      {
       "expr": "process_disk_write_bytes_second{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}-write-per-second"
      }
     ]
    },
    {
     "title": "Uptime Time $endpoint",
     "type": "timeseries",
     "description": "bytes read/write per second",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "process_uptime{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connected Time $endpoint",
     "type": "timeseries",
     "description": "bytes read/write per second",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "openmldb_connected_seconds_total{job=~\"$job\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{endpoint}}-{{role}}"
      }
     ]
    },
    {
     "title": "Process IO READ/WRITE Second $endpoint",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": " process_io_write_second{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": " process_io_read_second{job=~\"$component_job\", instance=~\"$endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tablet Specific status $tablet_endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query RPC Count $tablet_endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_openmldb_api_tablet_server_query_count\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Batch Request Query RPC  Count $tablet_endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " ({__name__=~\"rpc_server_.*_openmldb_api_tablet_server_sqlbatch_request_query_count\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Sub Query RPC Count $tablet_endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_openmldb_api_tablet_server_sub_query_count\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Sub Batch Request Query RPC Count $tablet_endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " ({__name__=~\"rpc_server_.*_openmldb_api_tablet_server_sub_batch_request_query_count\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RPC Query Count & Error Count $tablet_endpoint ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 28 },
     "repeat": "tablet_endpoint",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__ =~ \"rpc_server_.*_openmldb_api_tablet_server_query_count\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}-count"
      },
      {
       "expr": "{__name__ =~ \"rpc_server_.*_openmldb_api_tablet_server_query_error\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}-error"
      }
     ]
    },
    {
     "title": "RPC Sub Query Count & Error Count $tablet_endpoint ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 42 },
     "repeat": "tablet_endpoint",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_openmldb_api_tablet_server_sub_query_count\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}-count"
      },
      {
       "expr": "{__name__=~\"rpc_server_.*_openmldb_api_tablet_server_sub_query_error\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}-error"
      }
     ]
    },
    {
     "title": "RPC Batch Request Query Count & Error Count $tablet_endpoint ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 56 },
     "repeat": "tablet_endpoint",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__ =~ \"rpc_server_.*_openmldb_api_tablet_server_sqlbatch_request_query_count\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}-count"
      },
      {
       "expr": "{__name__ =~ \"rpc_server_.*_openmldb_api_tablet_server_sqlbatch_request_query_error\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}-error"
      }
     ]
    },
    {
     "title": "RPC Sub Batch Request Query Count & Error Count $tablet_endpoint ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 70 },
     "repeat": "tablet_endpoint",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__ =~ \"rpc_server_.*_openmldb_api_tablet_server_sub_batch_request_query_count\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}-count"
      },
      {
       "expr": "{__name__ =~ \"rpc_server_.*_openmldb_api_tablet_server_sub_batch_request_query_error\", job=~\"$component_job\", instance=~\"$tablet_endpoint\"}",
       "legendFormat": "{{instance}}-error"
      }
     ]
    },
    {
     "title": "Tablet $tablet_endpoint Memory (Application & Actual Memory)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 84 },
     "repeat": "tablet_endpoint",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "openmldb_tablet_memory_actual_used_bytes{endpoint=~\"$tablet_endpoint\", job=~\"$job\"}",
       "legendFormat": "tablet-actual-{{endpoint}}"
      },
      {
       "expr": "openmldb_tablet_memory_application_bytes{endpoint=~\"$tablet_endpoint\", job=~\"$job\"}",
       "legendFormat": "tablet-application-{{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tablet Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query RPC P99 Latency",
     "type": "timeseries",
     "description": "include subquery",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__ =~ \"rpc_server_.*_openmldb_api_tablet_server_query\"}",
       "legendFormat": "{{instance}}-{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "APIServer HTTP Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Methods P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\".*_http_method_latency\"}, \"quantile\", \"avg\", \"quantile\", \"\")",
       "legendFormat": "{{instance}}-{{method}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "HTTP Methods Max Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*_http_method_max_latency\"}",
       "legendFormat": "{{instance}}-{{method}}"
      }
     ]
    },
    {
     "title": "HTTP Methods QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*_http_method_qps\"}",
       "legendFormat": "{{instance}}-{{method}}"
      }
     ]
    },
    {
     "title": "HTTP Route Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*_http_route\"}",
       "legendFormat": "{{instance}}-{{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}