name: backport

# backport by issue a label (backport <target branch>) on merged PR 

on:
  pull_request_target:
    types: [closed, labeled]
jobs:
  backport:
    permissions:
      contents: write # so it can comment
      pull-requests: write # so it can create pull requests
    name: Backport Pull Request
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create backport PRs
        uses: korthout/backport-action@v2
