name: integration-test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  src-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: service up
        run: |
          docker compose --file docker-compose.yml up -d grafana

      - name: verbose services
        # ensure all services is up
        run: |
          sleep 60
          docker compose --file docker-compose.yml ps -a

      - name: verbose exporter log
        run: |
          docker compose --file docker-compose.yml logs openmldb-exporter

      - name: run tests
        run: |
          docker compose --file docker-compose.yml up --no-recreate --exit-code-from testing testing

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Monitoring integration test
          comment_title: Monitoring integration test
          files: |
            ./pytest.xml

  prod-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: service up
        run: |
          docker compose --file docker-compose.yml --env-file prod.env up -d grafana

      - name: run tests
        run: |
          docker compose --file docker-compose.yml --env-file prod.env up --no-recreate --exit-code-from testing testing
