name: integration-test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  compose-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: service up
        run: |
          docker compose --file docker-compose.yml up -d grafana

      - name: verbose services
        # ensure all services is up
        run: |
          sleep 10
          docker compose --file docker-compose.yml ps -a

      - name: run tests
        run: |
          docker compose --file docker-compose.yml up --no-recreate --exit-code-from testing testing

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./pytest.xml

