name: Python package

# necessary check for Python project, publish to PyPI performed locally

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  py-package:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          pip install --no-cache-dir poetry

      - name: verify
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          py_version=$(poetry version --short)
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          tag_version=${VERSION#v}
          if [[ $py_version != $tag_version ]] ; then
            echo "publish version does not match, $py_version vs $tag_version"
            exit 1
          fi

      - name: build
        run: |
          poetry install
          poetry build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./openmldb_mixin/openmldb_dashboard.json

